# Generated by Django 3.1 on 2020-08-24 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_started', models.BooleanField()),
                ('is_ended', models.BooleanField()),
            ],
        ),
    ]
