# Generated by Django 3.1 on 2020-08-25 09:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_started', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('is_failed', models.BooleanField(default=False)),
                ('error', models.TextField(null=True)),
                ('created_by', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_1', models.UUIDField(null=True)),
                ('player_2', models.UUIDField(null=True)),
                ('game_type', models.IntegerField(choices=[(1, 'PLAYER_BOT'), (2, 'PLAYER_PLAYER')])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
