# Generated by Django 3.1 on 2020-10-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='outcome',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.UUIDField(null=True),
        ),
    ]
