# Generated by Django 3.1 on 2020-08-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.UUIDField(default=123, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
