# Generated by Django 3.1 on 2020-10-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_auto_20201026_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='winner',
            new_name='winner_id',
        ),
    ]
