# Generated by Django 3.1 on 2020-11-27 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_auto_20201026_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
