# Generated by Django 3.1 on 2020-11-27 14:57

import coordinator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0005_auto_20201127_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default=coordinator.models.pick_random_username, max_length=128),
        ),
    ]
