# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/game/game.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/game/game.proto',
  package='game',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15proto/game/game.proto\x12\x04game\"5\n\x11\x43reateGameRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x11\n\tkuhn_type\x18\x02 \x01(\t\" \n\x12\x43reateGameResponse\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x0fListGameRequest\x12\r\n\x05token\x18\x01 \x01(\t\"$\n\x10ListGameResponse\x12\x10\n\x08game_ids\x18\x01 \x03(\t\"!\n\x0fPlayGameRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\"\x91\x03\n\x10PlayGameResponse\x12;\n\x05\x65vent\x18\x01 \x01(\x0e\x32,.game.PlayGameResponse.PlayGameResponseEvent\x12\x19\n\x11\x61vailable_actions\x18\x02 \x03(\t\x12\x12\n\nturn_order\x18\x04 \x01(\x05\x12\x11\n\tcard_rank\x18\x05 \x01(\t\x12\x12\n\ncard_image\x18\x06 \x01(\x0c\x12\x0f\n\x07inf_set\x18\x07 \x01(\t\x12\x18\n\x10round_evaluation\x18\x08 \x01(\x05\x12\x13\n\x0bgame_result\x18\t \x01(\t\x12\r\n\x05\x65rror\x18\n \x01(\t\"\x9a\x01\n\x15PlayGameResponseEvent\x12\x0b\n\x07Nothing\x10\x00\x12\x0c\n\x08\x43\x61rdDeal\x10\x01\x12\x0e\n\nNextAction\x10\x02\x12\r\n\tGameStart\x10\x03\x12\x0f\n\x0bRoundResult\x10\x04\x12\x0e\n\nGameResult\x10\x05\x12\t\n\x05\x43lose\x10\x06\x12\x10\n\x0cUpdateGameId\x10\x07\x12\t\n\x05\x45rror\x10\x08\x32\xd0\x01\n\x19GameCoordinatorController\x12=\n\x06\x43reate\x12\x17.game.CreateGameRequest\x1a\x18.game.CreateGameResponse\"\x00\x12\x37\n\x04List\x12\x15.game.ListGameRequest\x1a\x16.game.ListGameResponse\"\x00\x12;\n\x04Play\x12\x15.game.PlayGameRequest\x1a\x16.game.PlayGameResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)



_PLAYGAMERESPONSE_PLAYGAMERESPONSEEVENT = _descriptor.EnumDescriptor(
  name='PlayGameResponseEvent',
  full_name='game.PlayGameResponse.PlayGameResponseEvent',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Nothing', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CardDeal', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NextAction', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GameStart', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RoundResult', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GameResult', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Close', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UpdateGameId', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Error', index=8, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=475,
  serialized_end=629,
)
_sym_db.RegisterEnumDescriptor(_PLAYGAMERESPONSE_PLAYGAMERESPONSEEVENT)


_CREATEGAMEREQUEST = _descriptor.Descriptor(
  name='CreateGameRequest',
  full_name='game.CreateGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='game.CreateGameRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kuhn_type', full_name='game.CreateGameRequest.kuhn_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=84,
)


_CREATEGAMERESPONSE = _descriptor.Descriptor(
  name='CreateGameResponse',
  full_name='game.CreateGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='game.CreateGameResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=118,
)


_LISTGAMEREQUEST = _descriptor.Descriptor(
  name='ListGameRequest',
  full_name='game.ListGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='game.ListGameRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=152,
)


_LISTGAMERESPONSE = _descriptor.Descriptor(
  name='ListGameResponse',
  full_name='game.ListGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_ids', full_name='game.ListGameResponse.game_ids', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=190,
)


_PLAYGAMEREQUEST = _descriptor.Descriptor(
  name='PlayGameRequest',
  full_name='game.PlayGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='game.PlayGameRequest.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=225,
)


_PLAYGAMERESPONSE = _descriptor.Descriptor(
  name='PlayGameResponse',
  full_name='game.PlayGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='game.PlayGameResponse.event', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='available_actions', full_name='game.PlayGameResponse.available_actions', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='turn_order', full_name='game.PlayGameResponse.turn_order', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='card_rank', full_name='game.PlayGameResponse.card_rank', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='card_image', full_name='game.PlayGameResponse.card_image', index=4,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inf_set', full_name='game.PlayGameResponse.inf_set', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round_evaluation', full_name='game.PlayGameResponse.round_evaluation', index=6,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game_result', full_name='game.PlayGameResponse.game_result', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='game.PlayGameResponse.error', index=8,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PLAYGAMERESPONSE_PLAYGAMERESPONSEEVENT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=629,
)

_PLAYGAMERESPONSE.fields_by_name['event'].enum_type = _PLAYGAMERESPONSE_PLAYGAMERESPONSEEVENT
_PLAYGAMERESPONSE_PLAYGAMERESPONSEEVENT.containing_type = _PLAYGAMERESPONSE
DESCRIPTOR.message_types_by_name['CreateGameRequest'] = _CREATEGAMEREQUEST
DESCRIPTOR.message_types_by_name['CreateGameResponse'] = _CREATEGAMERESPONSE
DESCRIPTOR.message_types_by_name['ListGameRequest'] = _LISTGAMEREQUEST
DESCRIPTOR.message_types_by_name['ListGameResponse'] = _LISTGAMERESPONSE
DESCRIPTOR.message_types_by_name['PlayGameRequest'] = _PLAYGAMEREQUEST
DESCRIPTOR.message_types_by_name['PlayGameResponse'] = _PLAYGAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateGameRequest = _reflection.GeneratedProtocolMessageType('CreateGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMEREQUEST,
  '__module__' : 'proto.game.game_pb2'
  # @@protoc_insertion_point(class_scope:game.CreateGameRequest)
  })
_sym_db.RegisterMessage(CreateGameRequest)

CreateGameResponse = _reflection.GeneratedProtocolMessageType('CreateGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEGAMERESPONSE,
  '__module__' : 'proto.game.game_pb2'
  # @@protoc_insertion_point(class_scope:game.CreateGameResponse)
  })
_sym_db.RegisterMessage(CreateGameResponse)

ListGameRequest = _reflection.GeneratedProtocolMessageType('ListGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTGAMEREQUEST,
  '__module__' : 'proto.game.game_pb2'
  # @@protoc_insertion_point(class_scope:game.ListGameRequest)
  })
_sym_db.RegisterMessage(ListGameRequest)

ListGameResponse = _reflection.GeneratedProtocolMessageType('ListGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTGAMERESPONSE,
  '__module__' : 'proto.game.game_pb2'
  # @@protoc_insertion_point(class_scope:game.ListGameResponse)
  })
_sym_db.RegisterMessage(ListGameResponse)

PlayGameRequest = _reflection.GeneratedProtocolMessageType('PlayGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLAYGAMEREQUEST,
  '__module__' : 'proto.game.game_pb2'
  # @@protoc_insertion_point(class_scope:game.PlayGameRequest)
  })
_sym_db.RegisterMessage(PlayGameRequest)

PlayGameResponse = _reflection.GeneratedProtocolMessageType('PlayGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLAYGAMERESPONSE,
  '__module__' : 'proto.game.game_pb2'
  # @@protoc_insertion_point(class_scope:game.PlayGameResponse)
  })
_sym_db.RegisterMessage(PlayGameResponse)



_GAMECOORDINATORCONTROLLER = _descriptor.ServiceDescriptor(
  name='GameCoordinatorController',
  full_name='game.GameCoordinatorController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=632,
  serialized_end=840,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='game.GameCoordinatorController.Create',
    index=0,
    containing_service=None,
    input_type=_CREATEGAMEREQUEST,
    output_type=_CREATEGAMERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='List',
    full_name='game.GameCoordinatorController.List',
    index=1,
    containing_service=None,
    input_type=_LISTGAMEREQUEST,
    output_type=_LISTGAMERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Play',
    full_name='game.GameCoordinatorController.Play',
    index=2,
    containing_service=None,
    input_type=_PLAYGAMEREQUEST,
    output_type=_PLAYGAMERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMECOORDINATORCONTROLLER)

DESCRIPTOR.services_by_name['GameCoordinatorController'] = _GAMECOORDINATORCONTROLLER

# @@protoc_insertion_point(module_scope)
